#!/bin/sh

# Descripció:
# Comprova que estem a un Debian-like i amb els paquets necessari,
# la xarxa necessaria, etc

# Assignatura: GSX
# Autor: Josep M Banús Alsina
# versió: 2.0

echo "Exec: $0\n"

LANG=C	# output anglès: busco unmanaged

path=$(dirname "$(realpath "$0")")
definicions=$(find "$path" -name "definicions.sh" | head -1)
[ -z "$definicions" ] && echo "Falta el fitxer: definicions.sh" && exit 1
[ ! -f "$definicions" ] && echo "Falta +x a: definicions.sh" && exit 1
. "$definicions" >/dev/null 2>&1

debianLike=$(grep -i "debian\|ubuntu" /etc/os-release 2>/dev/null | wc -l)
[ $debianLike -eq 0 ] && \
echoError "Necessito un Debian per a poder crear els contenidors." && exit 1

distro=$(grep "^ID=" /etc/os-release | cut -f2 -d=)
[ "$distro" = "" ] && distro=$(grep "^ID_LIKE=" /etc/os-release | cut -f2 -d=)

fitxer=$relpath/paquets_requerits_host.sh
[ ! -f $fitxer ] && echoError "Falta el fitxer $fitxer" && exit 1
. $relpath/paquets_requerits_host.sh

comprova_paquet() {
	dpkg-query --status $1 >/dev/null 2>&1
	if [ $? -eq 0 ]; then 
		return 0
	else
		echoAvis "necessitaré el paquet $1"
		return 1
	fi
}

nfalten=0
for paq in $paquets
do
	comprova_paquet $paq
	nfalten=$(($nfalten+$?))
done
[ $nfalten -eq 0 ] && echo "OK: tenim tots els paquets requerits"

comprova_paquet systemd
[ $? -ne 0 ]  && echoError "Ha de ser una distro amb systemd" && exit 1

comprova_paquet net-tools >/dev/null
[ $? -ne 1 ] && echoError "Avís: Tens instal.lat net-tools (ifconfig etc) però no podràs usar-lo !"

comprova_paquet connman >/dev/null
[ $? -ne 1 ] && echoAvis "Tens instal.lat el gestor 'connman' i no és cmpatible." && exit 1

# comprovar l'estat de la xarxa i els seus gestors:
LANG=C

exitINTF=$(ip route get 1.1.1.1 2>/dev/null | grep -o "dev [^ ]\+" | cut -f2 -d' ')
nextHopIP=$(ip route get 1.1.1.1 2>/dev/null | grep -o "via [0-9.]\{7,15\}" | cut -f2 -d' ')
eswifi=$(networkctl list $outINTF 2>/dev/null | grep -ic wlan)
[ $eswifi -ne 0 ] && echoError "la connexió a Internet no pot ser per WiFi!\n" && exitINTF=""

test ! ${#exitINTF} -gt 0 -o ! ${#nextHopIP} -gt 0
internet=$?
gestio="Ningú"

ndgw=$(ip route 2>/dev/null | grep -v linkdown | grep -c default)
if [ $ndgw -gt 1 ]; then
	echoAvis "Hi ha diversos default gateway: podria causar problemes"
	ip route | grep -v linkdown | grep default
fi

comprova_paquet network-manager >/dev/null
if [ $? -eq 0 ]; then
	servei="NetworkManager"
	systemctl --no-pager status $servei >/dev/null 2>&1
	nm=$?	
	if [ $nm -eq 0 ]; then
		echo "El '$servei' està activat"
        else
		echo "El $servei actualment està aturat"
	fi
	if [ $nm -eq 0 -a ${#exitINTF} -gt 0 ]; then
		# gestiona la intf de sortida ?
		si=$(nmcli dev show $exitINTF | grep -v external | grep -c "\<connected")
		if [ $si -eq 0 ]; then
			echo "No gestiona $exitINTF"
		else
			echoAvis "El $servei gestiona $exitINTF"
			nmcli dev | grep --color $exitINTF 
			gestio=$servei
		fi
	fi
fi

servei="systemd-networkd"
systemctl --no-pager status $servei >/dev/null 2>&1
nd=$?
if [ $nd -eq 0 ]; then
	echo "El '$servei' està activat"
	if [ ${#exitINTF} -gt 0 ]; then
		si=$(networkctl status $exitINTF 2>/dev/null | grep -io "state.*" | grep -c unmanaged)
		if [ $si -eq 0 ]; then
			echoAvis "El $servei gestiona $exitINTF"
			gestio=$servei
		else
			echo "No gestiona $exitINTF"
		fi
	fi
else
	echo "El $servei actualment està aturat"
fi

if [ ${#exitINTF} -gt 0 ]; then
	# comprovar ifupdown
	systemctl --no-pager status networking >/dev/null 2>&1
	[ $? -ne 0 ]  && echo "El servei de xarxa ifupdown no està executant-se"

	if [ -f /etc/network/interfaces ]; then
		n=$(/sbin/ifquery $exitINTF 2>/dev/null | wc -l)
		if [ $n -gt 0 ]; then
			echoAvis "ifupdown té configurada $exitINTF"
			ps -o pid,cmd -C dhclient | grep --color $exitINTF
			gestio="ifupdown"
		else 
			echo "No gestiona $exitINTF"
		fi
	fi
fi

echo
# comprovar el DNS
dns=0
if [ ! -f /etc/resolv.conf ]; then
       echoAvis "Sembla que no tenim el resolver configurat a /etc/resolv.conf"
else
	if [ -L /etc/resolv.conf ]; then
		echo "/etc/resolv.conf és un symlink"
		ls -l /etc/resolv.conf
	fi
	dns=$(grep -c "127.0.0.53" /etc/resolv.conf)
	if [ $dns -gt 0 ]; then
		dns=$(grep -c "systemd-resolved" /etc/resolv.conf)
		if [ $dns -gt 0 ]; then
			echo "OK: resolv.conf generat per 'systemd-resolved'"
		else
			dns=$(grep -c "Generated by NetworkManager" /etc/resolv.conf)
			if [ $dns -gt 0 ]; then
				echo "OK: resolv.conf generat per 'NetworkManager'"
			else
				echoAvis "OK: nameservers gestionats per un gestor local desconegut"
			fi
		fi
		dns=0	# es mostran més avall
	else
		echo "Servidors a resolv.conf:"
		dns=$(grep -c "^nameserver" /etc/resolv.conf)
		grep --color "^nameserver" /etc/resolv.conf
	fi
fi

systemctl --no-pager status systemd-resolved >/dev/null 2>&1
if [ $? -eq 0 ]; then
	echo "El 'systemd-resolved' està actiu."
	if [ ${#exitINTF} -gt 0 -a $dns -eq 0 ]; then
		dns=$(resolvectl dns $exitINTF | grep -c "[0-9\.]\{7,17\}")
		resolvectl dns $exitINTF | grep -o "[0-9\.]\{7,17\}"
	fi
	if [ $dns -eq 0 ]; then
		# no estan per interfície però sí al Global:
		resolvectl | grep -o "\([0-9\]\{1,3\}\.\)\{3\}.[0-9]\{1,3\}" | sort -u
	fi
fi

echo
if [ $internet -eq 1 ]; then
	echo "OK: Internet per $exitINTF nextHop $nextHopIP"
else
	echoError "Necessito accés a Internet (per cable)"
	exit 1
fi

exit 0
